### ISSUE TITLE
Espanol fixes. 

### ISSUE THREAD

**Issue by michaelJwilson** [michaelJwilson/desihigh#43]
-- Update home README.
-- Still NY Time (English) for Life on Venus.  (MayaToDESI).
-- Risa Ted talk -> ?  (nbody).
-- Other?

**Comment by michaelJwilson** [comment]
@alxogm @jsuarez314 What's your sense for how update to date the Spanish is at the minute?  I see the home README has fallen behind quite a bit.

**Comment by alxogm** [comment]
@michaelJwilson sorry for the slow replay, yes I think the easiest way will be when a PR is done on the English version create an issue like this for the spanish speakers to fix it. I'll try to take a look at where are we behind and fix it.  I'm a bit afraid that sometimes we'll be able to fix them at the moment and some other times we will not as in this case that. I'm thinking a undergraduate student can work on this as part of their service time, I worked with one last year for the translations of the posts in the webpage and it worked well, so I might try that.

**Comment by jsuarez314** [comment]
Hi @michaelJwilson, I am in accord with the methodology purposed by @alxogm, so I would collaborate with it while an undergraduate student will be selected. 

Related to the duplicated files I propose to use the site package instead to create new ones.

**Comment by michaelJwilson** [comment]
No problem!  @alxogm all sounds good to me, whatever you can do to keep up. 

@jsuarez314 site package sounds perfect.  If you get a chance, could you try to implement this change?

**Comment by jsuarez314** [comment]
@michaelJwilson You can count on me to proceed.

**Comment by michaelJwilson** [comment]
@jsuarez314 Travis was still failing so it was necessary to revisit the approach. 

For code, let's copy into Espanol where necessary, e.g. for the tools directory. 
For data, let's use 

```from pkg_resources import resource_filename

e.g. fname = resoure_filename('desihigh', 'dat/hubble.dat')

I had the English working but had to break it further given the Spanish, e.g. by moving the images directory aswell.
Would you be able to revisit Espanol according to the rules above?  If that doesn't work, let me know.  Thanks!

**Comment by jsuarez314** [comment]
@michaelJwilson  ok, I will probe this method

**Comment by michaelJwilson** [comment]
@jsuarez314 Great, thank you!  We'll need this up and running for the UNAM Fest.  So hopefully the time frame for a first test is a week or two?
