### ISSUE TITLE
Colab badge

### ISSUE THREAD

**Issue by michaelJwilson** [michaelJwilson/desihigh#74]
https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb

**Comment by cylammarco** [comment]
Is this a replacement of binder or a parallel development along with it?

**Comment by michaelJwilson** [comment]
Ha, you expect me to remember :p  I think it was in parallel, on the basis that the students were much more used to collaborate and they had the ability to save work.  I've used your old email address to add you to a slack, let me know if that didn't work!

**Comment by michaelJwilson** [comment]
Done.
