### ISSUE TITLE
Images are not loaded correctly in Colab

### ISSUE THREAD

**Issue by alxogm** [michaelJwilson/desihigh#87]
All images loaded with this syntax

`![title](desihigh/images/Climate.png)`

are not loaded correctly in Colab. Changing to 

```
from   IPython.display   import Image
Imge(filename="desihigh/images/Climate.png")
```
works well, and is already used in some notebooks. 

@michaelJwilson Can we make the change, or do you want to try some other solution?

**Comment by michaelJwilson** [comment]
Handled, eventually by #93, 

![title](desihigh/images/Climate.png)

does in fact work, providing io is handled via linking notebooks through GitHub.
